import { Typography, Brushes } from "../styling/styling.slint";

export component Title1 inherits Text {
    font-size: Typography.title-1.font-size;
    font-weight: Typography.title-1.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component Title2 inherits Text {
    font-size: Typography.title-2.font-size;
    font-weight: Typography.title-2.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component Title3 inherits Text {
    font-size: Typography.title-3.font-size;
    font-weight: Typography.title-3.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component Title4 inherits Text {
    font-size: Typography.title-4.font-size;
    font-weight: Typography.title-4.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component Heading inherits Text {
    font-size: Typography.heading.font-size;
    font-weight: Typography.heading.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component CapitionHeading inherits Text {
    font-size: Typography.caption-heading.font-size;
    font-weight: Typography.caption-heading.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component Body inherits Text {
    font-size: Typography.body.font-size;
    font-weight: Typography.body.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component Caption inherits Text {
    font-size: Typography.caption.font-size;
    font-weight: Typography.caption.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}

export component MonoText inherits Text {
    font-size: Typography.mono-text.font-size;
    font-weight: Typography.mono-text.font-weight;
    font-family: Typography.default-font-family;
    color: Brushes.on-bg-color;
    overflow: elide;
}