// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

import { Brushes, Palette, Settings, Icons } from "../styling/styling.slint";

export component Slider {
    callback changed(/* value */ float);

    in property<float> maximum: 100;
    in property<float> minimum: 0;
    in property<bool> enabled <=> i-touch-area.enabled;
    out property<bool> has-focus: i-focus-scope.has-focus;
    in-out property<float> value;

    min-height: 20px;
    vertical-stretch: 0;
    horizontal-stretch: 1;
    accessible-role: slider;
    accessible-value: root.value;
    accessible-value-minimum: root.minimum;
    accessible-value-maximum: root.maximum;
    accessible-value-step: (root.maximum - root.minimum) / 100;

    i-rail := Rectangle {
        height: 4px;
        background: Palette.neutral-6;
        border-radius: 2px;
    }

    i-track := Rectangle {
        x: 0;
        height: i-rail.height;
        background: Brushes.accent-color;
        border-radius: i-rail.border-radius;
        width: i-thumb.x + (i-thumb.width / 2);
    }

    i-thumb := Rectangle {
        x: (parent.width - self.width) * (root.value - root.minimum) / (root.maximum - root.minimum);
        width: 20px;
        height: self.width;
        border-radius: 10px;
        background: Brushes.accent-color;

        i-state-layer := Rectangle {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            width: 26px;
            height: self.width;
            border-radius: self.width / 2;

             // focus border
             if (root.has-focus) : Rectangle {
                x: -3px;
                y: -3px;
                width: parent.width + 6px;
                height: parent.height + 6px;
                border-width: 1px;
                border-color: Brushes.accent-color;
                border-radius: parent.border-radius + 3px;
            }
        }
    }

    i-touch-area := TouchArea {
        property <float> pressed-value;

        width: parent.width;
        height: parent.height;

        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                self.pressed-value = root.value;
            }
        }

        moved => {
            if (self.enabled && self.pressed) {
                root.value = max(root.minimum, min(root.maximum,
                    self.pressed-value + (i-touch-area.mouse-x - i-touch-area.pressed-x) * (root.maximum - root.minimum) / (root.width - i-thumb.width)));
                root.changed(root.value);
            }
        }
    }

    i-focus-scope := FocusScope {
        x: 0;
        width: 0;

        key-pressed(event) => {
            if (self.enabled && event.text == Key.RightArrow) {
                root.value = Math.min(root.value + 1, root.maximum);
                accept
            } else if (self.enabled && event.text == Key.LeftArrow) {
                root.value = Math.max(root.value - 1, root.minimum);
                accept
            } else {
                reject
            }
        }
    }

    states [
        disabled when !root.enabled : {
           root.opacity: 0.5;
        }
        pressed when (i-touch-area.pressed &&  i-touch-area.has-hover) || i-focus-scope.has-focus : {
            i-state-layer.background: Brushes.pressed-state-color;
        }
        hover when i-touch-area.has-hover : {
            i-state-layer.background: Brushes.hover-state-color;
        }
    ]
}