import { ExtendedTouchArea, Body } from "../components/components.slint";
import { Brushes, Palette } from "../styling/styling.slint";

export component Switch {
    callback toggled(/* checked */ bool);

    in property <bool> enabled <=> i-extended-touch-area.enabled;
    in property <string> text <=> i-body.text;
    in-out property <bool> checked;

    min-width: max(48px, i-layout.min-width);
    height: max(24px, i-layout.min-height);

    i-layout := HorizontalLayout {
        spacing: 8px;

        i-extended-touch-area := ExtendedTouchArea {
            y: (parent.height - self.height) / 2;
            width: 48px;
            height: 24px;
            border-radius: 12px;
            background: Palette.neutral-5;

            i-thumb := Rectangle {
                x: 2px;
                width: 20px;
                height: self.width;
                border-radius: 10px;
                background: Palette.neutral-2;
            }

            clicked => {
                root.checked = !root.checked;
                root.toggled(root.checked);
            }
        }

        i-body := Body {
            vertical-alignment: center;
            color: Palette.neutral-9;
        }
    }

    states [
        checked when root.checked : {
            i-thumb.x: i-extended-touch-area.width - i-thumb.width - 2px;
            i-extended-touch-area.background: Brushes.accent-color;
        }
    ]
}