import { CosmicWindow, Title1, Title2, Title3, Title4, Heading, CapitionHeading, Body, Caption, MonoText }
    from "/Users/flovansl/Projects/cosmic/slibcosmic/ui/components/components.slint";
export { CosmicWindow, Title1, Title2, Title3, Title4, Heading, CapitionHeading, Body, Caption, MonoText  }

import { Brushes, TextStyle, Typography } from "/Users/flovansl/Projects/cosmic/slibcosmic/ui/styling/styling.slint";
export { Brushes, TextStyle, Typography }