export global Icons {
    out property <image> arrow-right: @image-url("../../res/Icons/cosmic-arrow-right.svg");
    out property <image> bluetooth: @image-url("../../res/Icons/cosmic-bluetooth.svg");
    out property <image> checkmark: @image-url("../../res/Icons/cosmic-checkmark.svg");
    out property <image> close: @image-url("../../res/Icons/cosmic-close.svg");
    out property <image> drop-down: @image-url("../../res/Icons/cosmic-dropdown.svg");
    out property <image> error: @image-url("../../res/Icons/cosmic-error.svg");
    out property <image> eye: @image-url("../../res/Icons/cosmic-eye.svg");
    out property <image> link: @image-url("../../res/Icons/cosmic-link.svg");
    out property <image> lock: @image-url("../../res/Icons/cosmic-lock.svg");
    out property <image> minus: @image-url("../../res/Icons/cosmic-minus.svg");
    out property <image> plus: @image-url("../../res/Icons/cosmic-plus.svg");
    out property <image> settings: @image-url("../../res/Icons/cosmic-settings.svg");
}