export global Icons {
    out property <image> arrow-right: @image-url("../../res/Icons/cosmic-arrow-right.svg");
    out property <image> bluetooth: @image-url("../../res/Icons/cosmic-bluetooth.svg");
    out property <image> checkmark: @image-url("../../res/Icons/cosmic-checkmark.svg");
    out property <image> drop-down: @image-url("../../res/Icons/cosmic-dropdown.svg");
    out property <image> settings: @image-url("../../res/Icons/cosmic-settings.svg");
}