import "../../res/Fira/FiraMono-Regular.otf";
import "../../res/Fira/FiraSans-Light.otf";
import "../../res/Fira/FiraSans-Regular.otf";
import "../../res/Fira/FiraSans-SemiBold.otf";

export struct TextStyle {
    font-size: length,
    font-weight: int,
}

export global Typography {
    out property <int> light-font-weight: 300;
    out property <int> regular-font-weight: 400;
    out property <int> semibold-font-weight: 600;
    out property <string> default-font-family: "Fira Sans";
    out property <string> mono-font-family: "Fira Mono";

    out property <TextStyle> title-1: {
        font-size: 32px,
        font-weight: light-font-weight
    };
    out property <TextStyle> title-2: {
        font-size: 28px,
        font-weight: regular-font-weight
    };
    out property <TextStyle> title-3: {
        font-size: 24px,
        font-weight: regular-font-weight
    };
    out property <TextStyle> title-4: {
        font-size: 20px,
        font-weight: regular-font-weight
    };
    out property <TextStyle> heading: {
        font-size: 14px,
        font-weight: semibold-font-weight
    };
    out property <TextStyle> caption-heading: {
        font-size: 10px,
        font-weight: semibold-font-weight
    };
    out property <TextStyle> body: {
        font-size: 14px,
        font-weight: regular-font-weight
    };
    out property <TextStyle> caption: {
        font-size: 10px,
        font-weight: regular-font-weight
    };
    out property <TextStyle> mono-text: {
        font-size: 14px,
        font-weight: regular-font-weight
    };
}