export struct TextStyle {
    font-size: length,
    font-weight: int,
}

export global Typography {
    out property <TextStyle> title-1: {
        font-size: 32px,
        font-weight: 300
    };
    out property <TextStyle> title-2: {
        font-size: 28px,
        font-weight: 400
    };
    out property <TextStyle> title-3: {
        font-size: 24px,
        font-weight: 400
    };
    out property <TextStyle> title-4: {
        font-size: 20px,
        font-weight: 400
    };
    out property <TextStyle> heading: {
        font-size: 14px,
        font-weight: 600
    };
    out property <TextStyle> caption-heading: {
        font-size: 10px,
        font-weight: 600
    };
    out property <TextStyle> body: {
        font-size: 14px,
        font-weight: 400
    };
    out property <TextStyle> caption: {
        font-size: 10px,
        font-weight: 400
    };
    out property <TextStyle> mono-text: {
        font-size: 14px,
        font-weight: 400
    };
}